# humanizer/phrases.py
# Rule-based phrase dictionaries — no AI API needed

# ── PASS 1: AI Phrase → Human Phrase replacements ─────────────────────────────
AI_PHRASES = {
    # Transition phrases
    "in order to": "to",
    "in order for": "so that",
    "so as to": "to",
    "with the aim of": "to",
    "for the purpose of": "to",
    "with the purpose of": "to",

    # Certainty / importance filler
    "it is important to note that": "notably,",
    "it is worth noting that": "worth noting,",
    "it should be noted that": "notably,",
    "it is essential to": "we must",
    "it is crucial to": "we need to",
    "it is necessary to": "we need to",
    "it is vital that": "critically,",
    "it is imperative that": "we must ensure",
    "it is important that": "we need to ensure",
    "needless to say": "clearly",
    "it goes without saying": "clearly",
    "last but not least": "finally",
    "it is safe to say": "arguably",
    "it can be argued that": "arguably,",
    "it is widely accepted that": "most agree that",
    "it is generally agreed that": "most agree that",
    "there is no doubt that": "clearly,",
    "without a doubt": "clearly",
    "it is beyond question": "clearly",
    "it must be acknowledged": "admittedly,",
    "it must be recognized": "notably,",

    # Demonstrative openers
    "this is exactly why": "that is why",
    "this is the reason why": "which is why",
    "this means that": "meaning",
    "this ensures that": "this way",
    "this allows us to": "allowing us to",
    "this helps to": "helping",
    "this makes it possible to": "making it possible to",
    "this provides a": "offering a",
    "this results in": "resulting in",
    "this leads to": "leading to",
    "this contributes to": "contributing to",
    "this enables": "this lets",
    "this demonstrates": "this shows",
    "this illustrates": "this shows",
    "this highlights": "this points to",
    "this underscores": "this reinforces",
    "this reflects": "this shows",
    "this indicates": "this suggests",

    # Modern ChatGPT Cliches (Future-proofing)
    "delve into": "explore",
    "delving into": "exploring",
    "delved into": "explored",
    "delves into": "explores",
    "a rich tapestry": "a complex mix",
    "the tapestry of": "the mix of",
    "a testament to": "proof of",
    "at the intersection of": "where these meet",
    "a myriad of": "many",
    "myriad": "many",
    "orchestrate": "manage",
    "orchestrated": "managed",
    "orchestrates": "manages",
    "orchestrating": "managing",
    "symbiotic relationship": "mutual relationship",
    "rapidly evolving digital landscape": "modern world",
    "in today's digital landscape": "today",
    "it's not merely": "it's not just",
    "is not merely": "is not just",
    "foster": "encourage",
    "fosters": "encourages",
    "fostered": "encouraged",
    "fostering": "encouraging",
    "catalyst": "driver",
    "serve as a catalyst": "drive the change",
    "embark on a journey": "begin",
    "unleash the power": "use",
    "unleash": "release",
    "unleashes": "releases",
    "unleashed": "released",
    "unleashing": "releasing",
    "revolutionize the way": "change how",
    "revolutionize": "transform",
    "revolutionized": "transformed",
    "revolutionizes": "transforms",
    "revolutionizing": "transforming",
    "underscore the importance": "highlight the need",
    "unlocking the potential": "using the potential",
    "beacon of": "symbol of",
    "a profound impact": "a big impact",
    "sheds light on": "explains",
    "meticulously": "carefully",
    "democratize access": "open access",
    "democratize": "open up",
    "democratizes": "opens up",
    "democratized": "opened up",
    "democratizing": "opening up",
    "empower individuals": "help people",
    "paradigm shift": "major change",
    "paradigm shifts": "major changes",
    "at the forefront of": "leading",
    "spearheading": "leading",
    "in the grand scheme of things": "overall",
    "a mosaic of": "a mix of",
    "seamless integration": "smooth integration",
    "actionable insights": "useful insights",
    "leverage the power of": "use",
    "catalyze": "cause",
    "frictionless": "smooth",
    "hyper-connected": "connected",
    "unprecedented scale": "huge scale",
    "exponential growth": "rapid growth",
    "cognitive load": "mental effort",
    "synergize": "combine",
    "transcend boundaries": "go beyond limits",
    "elevate the experience": "improve the experience",
    "a multifaceted approach": "a complex approach",
    "nuanced understanding": "detailed understanding",
    "it is important to recognize": "we should note",
    "it is crucial to recognize": "we must note",
    "a symphony of": "a mix of",
    "harmonious": "balanced",
    "inextricably linked": "closely tied",
    "ever-evolving": "changing",

    # Verb stuffing
    "ensure that": "make sure",
    "ensures that": "makes sure",
    "ensuring that": "making sure",
    "leverage": "use",
    "leveraging": "using",
    "leveraged": "used",
    "utilize": "use",
    "utilizes": "uses",
    "utilizing": "using",
    "utilized": "used",
    "facilitate": "support",
    "facilitates": "supports",
    "facilitating": "supporting",
    "implement": "build",
    "implementing": "building",
    "implemented": "built",
    "demonstrate": "show",
    "demonstrates": "shows",
    "demonstrating": "showing",
    "demonstrated": "showed",
    "obtain": "get",
    "obtains": "gets",
    "obtaining": "getting",
    "obtained": "got",
    "commence": "start",
    "commences": "starts",
    "commencing": "starting",
    "commenced": "started",
    "terminate": "end",
    "terminates": "ends",
    "terminating": "ending",
    "terminated": "ended",
    "endeavor": "try",
    "endeavors": "tries",
    "endeavoring": "trying",
    "endeavored": "tried",
    "ascertain": "find out",
    "ascertains": "finds out",
    "attempt to": "try to",
    "attempts to": "tries to",
    "in an attempt to": "trying to",
    "in an effort to": "trying to",
    "strive to": "try to",
    "strives to": "tries to",
    "endeavour to": "try to",
    "seek to": "aim to",
    "seeks to": "aims to",
    "aim to achieve": "try to reach",
    "mitigate": "reduce",
    "mitigates": "reduces",
    "mitigating": "reducing",
    "augment": "improve",
    "augments": "improves",
    "augmenting": "improving",
    "enhance": "improve",
    "enhances": "improves",
    "enhancing": "improving",
    "optimise": "improve",
    "optimize": "improve",
    "optimises": "improves",
    "optimizes": "improves",
    "maximise": "maximize",
    "capitalise on": "make the most of",
    "capitalize on": "make the most of",
    "prioritise": "prioritize",
    "necessitate": "require",
    "necessitates": "requires",

    # Adjective stuffing
    "comprehensive": "thorough",
    "robust": "strong",
    "seamless": "smooth",
    "innovative": "new",
    "cutting-edge": "modern",
    "state-of-the-art": "modern",
    "groundbreaking": "notable",
    "revolutionary": "significant",
    "transformative": "meaningful",
    "pivotal": "key",
    "paramount": "most important",
    "imperative": "essential",
    "optimal": "best",
    "streamlined": "efficient",
    "scalable solution": "solution that scales",
    "holistic approach": "broad approach",
    "proactive approach": "forward-looking approach",
    "multifaceted": "complex",
    "intricate": "detailed",
    "nuanced": "subtle",
    "diverse": "varied",
    "dynamic": "flexible",
    "synergistic": "complementary",
    "collaborative": "joint",
    "strategic": "planned",
    "critical": "important",
    "fundamental": "basic",
    "integral": "central",
    "indispensable": "essential",
    "prerequisite": "requirement",
    "sophisticated": "advanced",
    "versatile": "flexible",
    "significant": "notable",
    "substantial": "large",
    "considerable": "notable",
    "remarkable": "notable",
    "exceptional": "unusual",

    # Adverb stuffing
    "effectively": "well",
    "efficiently": "quickly",
    "seamlessly": "smoothly",
    "significantly": "considerably",
    "substantially": "considerably",
    "tremendously": "greatly",
    "tremendously helpful": "very helpful",
    "incredibly": "quite",
    "extremely": "very",
    "exceptionally": "particularly",
    "remarkably": "notably",
    "undoubtedly": "clearly",
    "undeniably": "clearly",
    "inherently": "by nature",
    "fundamentally": "at its core",
    "ultimately": "in the end",
    "essentially": "basically",
    "primarily": "mainly",
    "predominantly": "mostly",
    "systematically": "methodically",
    "comprehensively": "thoroughly",
    "strategically": "deliberately",
    "proactively": "ahead of time",
    "continuously": "constantly",
    "consistently": "regularly",
    "accordingly": "so",
    "subsequently": "later",
    "simultaneously": "at the same time",
    "collectively": "together",
    "individually": "separately",
    "respectively": "in that order",
    "specifically": "in particular",
    "particularly": "especially",
    "generally": "usually",
    "typically": "usually",
    "traditionally": "historically",
    "conventionally": "typically",

    # Conclusion markers
    "in conclusion": "overall",
    "to conclude": "to sum up",
    "to summarize": "in short",
    "in summary": "in short",
    "as a result": "so",
    "as a consequence": "that's why",
    "consequently": "so",
    "therefore": "so",
    "thus": "so",
    "hence": "which means",
    "as mentioned earlier": "as discussed",
    "as mentioned above": "as noted above",
    "as stated above": "as noted",
    "as discussed above": "as covered earlier",
    "the aforementioned": "the above",
    "to reiterate": "to restate",
    "by extension": "and by implication",
    "in other words": "put differently",
    "put simply": "simply put",
    "that is to say": "meaning",

    # Introduction markers
    "first and foremost": "first",
    "first of all": "first",
    "to begin with": "to start",
    "in the first place": "initially",
    "to kick things off": "to start",
    "moving forward": "going forward",
    "having said that": "that said",
    "with that being said": "that said",
    "with that in mind": "keeping that in mind",
    "it is worth mentioning": "worth mentioning",
    "as we move forward": "going forward",
    "as previously mentioned": "as noted",
    "as noted previously": "as discussed",
    "building on this": "following from this",
    "in light of this": "given this",
    "taking this into consideration": "considering this",

    # Passive / formal constructs
    "can be seen": "shows",
    "can be observed": "shows",
    "can be found": "exists",
    "can be noted": "is notable",
    "was designed to": "was built to",
    "is intended to": "aims to",
    "are intended to": "aim to",
    "is utilized to": "is used to",
    "is employed to": "is used to",
    "play a crucial role": "are central",
    "plays a crucial role": "is central",
    "plays a key role": "is key",
    "play a key role": "are key",
    "plays a vital role": "is essential",
    "play a vital role": "are essential",
    "plays an important role": "matters a lot",
    "a wide range of": "various",
    "a wide variety of": "various",
    "a large number of": "many",
    "a significant number of": "many",
    "a considerable number of": "quite a few",
    "on a daily basis": "every day",
    "on a regular basis": "regularly",
    "in a timely manner": "on time",
    "in an effective manner": "effectively",
    "in a systematic manner": "methodically",
    "with relative ease": "fairly easily",
    "to a great extent": "largely",
    "to a large extent": "largely",
    "to a certain extent": "somewhat",
    "in many ways": "often",
    "in some ways": "somewhat",
    "across the board": "overall",
    "at every level": "throughout",
    "at all levels": "throughout",
    "in all aspects": "in every way",

    # Filler / padding
    "due to the fact that": "because",
    "owing to the fact that": "because",
    "in light of the fact that": "given that",
    "for the simple reason that": "because",
    "in the event that": "if",
    "in the case that": "if",
    "under the circumstances": "given this",
    "with regard to": "regarding",
    "with respect to": "regarding",
    "in relation to": "regarding",
    "in terms of": "for",
    "from the perspective of": "from",
    "from a technical standpoint": "technically",
    "from an operational standpoint": "operationally",
    "at this point in time": "now",
    "at the present time": "currently",
    "at the current time": "currently",
    "in today's world": "today",
    "in today's day and age": "today",
    "in this day and age": "today",
    "on the other hand": "alternatively",
    "on the contrary": "in contrast",
    "by the same token": "similarly",
    "along the same lines": "similarly",
    "in the same vein": "similarly",
    "as opposed to": "rather than",
    "as compared to": "compared to",
    "vis-à-vis": "compared to",
    "with reference to": "regarding",
    "pertaining to": "about",
    "in conjunction with": "alongside",
    "in tandem with": "alongside",
    "in line with": "consistent with",
    "in accordance with": "following",
    "in compliance with": "following",

    # AI-specific phrasing
    "shed light on": "clarify",
    "shedding light on": "clarifying",
    "navigate the complexities": "handle the challenges",
    "navigates the complexities": "handles the challenges",
    "navigating the complexities": "handling the challenges",
    "navigated the complexities": "handled the challenges",
    "bridge the gap": "close the gap",
    "bridges the gap": "closes the gap",
    "bridged the gap": "closed the gap",
    "bridging the gap": "closing the gap",
    "at the heart of": "central to",
    "at the core of": "central to",
    "pave the way": "make it possible",
    "paves the way": "makes it possible",
    "paving the way": "making it possible",
    "paved the way": "made it possible",
    "take into account": "consider",
    "takes into account": "considers",
    "taking into account": "considering",
    "come into play": "become relevant",
    "comes into play": "becomes relevant",
    "came into play": "became relevant",
    "coming into play": "becoming relevant",
    "empower": "help",
    "empowers": "helps",
    "empowered": "helped",
    "empowering": "helping",
    "harness": "use",
    "harnesses": "uses",
    "harnessed": "used",
    "harnessing": "using",
    "fast-paced": "fast-moving",
    "robust framework": "strong structure",
    "in a nutshell": "briefly",
    "to put it simply": "simply put",
    "it is clear that": "clearly,",
    "needless to say,": "clearly,",
    "it is evident that": "clearly,",
    "it is apparent that": "clearly,",
    "boils down to": "comes down to",
    "at the end of the day": "ultimately",
    "when all is said and done": "in the end",
    "all things considered": "overall",
    "all in all": "overall",
    "by and large": "generally",
    "more often than not": "usually",
    "for the most part": "mostly",
    "in the long run": "over time",
    "in the short term": "for now",
    "go hand in hand": "are closely linked",
    "goes hand in hand": "is closely linked",
    "stands out": "is notable",
    "set the stage": "prepare the ground",
    "sets the stage": "prepares the ground",
    "take center stage": "become central",
    "takes center stage": "becomes central",
    "on the cutting edge": "at the forefront",
    "stay ahead of the curve": "keep pace",
    "think outside the box": "approach differently",
    "move the needle": "make a difference",
    "moves the needle": "makes a difference",
    "game changer": "significant shift",
    "game-changing": "significant",
    "best practices": "recommended approaches",
    "key takeaway": "main point",
    "key takeaways": "main points",
    "going forward": "from here",
    "the bottom line": "in short",
    "a key component": "an important part",
    "key components": "important parts",
    "a core component": "a central part",
    "core components": "central parts",
    "a critical component": "an essential part",
    "critical components": "essential parts",
    "play a pivotal role": "are central",
    "plays a pivotal role": "is central",
    "of utmost importance": "very important",
    "of paramount importance": "most important",
    "in the foreseeable future": "soon",
    "in the near future": "soon",
    "in the coming years": "in years ahead",
    "in the coming months": "in the months ahead",
    "on a global scale": "globally",
    "on a large scale": "at scale",
    "on a small scale": "in a limited way",
    "across various domains": "across fields",
    "across multiple domains": "across fields",
    "in various contexts": "in different situations",
    "in multiple contexts": "in many situations",
    "real-world applications": "practical uses",
    "real-world scenarios": "practical situations",
    "in practice": "practically",
    "in theory": "theoretically",
    "in principle": "theoretically",
    "worth mentioning that": "worth noting that",
}

# ── PASS 2: Intensifiers to remove or soften ──────────────────────────────────
INTENSIFIERS = {
    "very important": "important",
    "very complex": "complex",
    "very simple": "simple",
    "very easy": "easy",
    "very difficult": "difficult",
    "very challenging": "challenging",
    "very helpful": "helpful",
    "very useful": "useful",
    "very powerful": "powerful",
    "very effective": "effective",
    "very efficient": "efficient",
    "very common": "common",
    "very popular": "popular",
    "very different": "different",
    "very similar": "similar",
    "very large": "large",
    "very small": "small",
    "very fast": "fast",
    "very slow": "slow",
    "very high": "high",
    "very low": "low",
    "very good": "good",
    "very bad": "bad",
    "very clear": "clear",
    "very obvious": "obvious",
    "very specific": "specific",
    "very detailed": "detailed",
    "very accurate": "accurate",
    "very reliable": "reliable",
    "very secure": "secure",
    "very strong": "strong",
    "very weak": "weak",
    "very easy to use": "easy to use",
    "very hard to": "hard to",
    "very much": "greatly",
    "very well": "well",
    "very little": "little",
    "very few": "few",
    "very many": "many",
    "very much like": "similar to",
    "quite complex": "complex",
    "quite simple": "simple",
    "quite effective": "effective",
    "quite important": "important",
    "quite useful": "useful",
    "quite different": "different",
    "quite challenging": "challenging",
    "quite significant": "significant",
    "quite large": "large",
    "quite small": "small",
    "quite common": "common",
    "quite popular": "popular",
    "quite similar": "similar",
    "extremely important": "critical",
    "extremely helpful": "invaluable",
    "extremely complex": "very complex",
    "extremely powerful": "powerful",
    "extremely difficult": "difficult",
    "extremely effective": "effective",
    "extremely useful": "useful",
    "highly significant": "significant",
    "highly effective": "effective",
    "highly efficient": "efficient",
    "highly reliable": "reliable",
    "highly accurate": "accurate",
    "highly relevant": "relevant",
    "highly recommended": "recommended",
    "highly important": "important",
    "highly beneficial": "beneficial",
    "highly valuable": "valuable",
    "absolutely essential": "essential",
    "absolutely necessary": "necessary",
    "absolutely critical": "critical",
    "absolutely crucial": "crucial",
    "absolutely vital": "vital",
    "completely different": "different",
    "completely new": "new",
    "completely free": "free",
    "totally different": "different",
    "entirely different": "different",
    "entirely new": "new",
    "deeply important": "important",
    "deeply significant": "significant",
    "profoundly important": "important",
    "incredibly important": "important",
    "incredibly useful": "useful",
    "incredibly powerful": "powerful",
    "remarkably effective": "effective",
    "remarkably simple": "simple",
    "exceptionally powerful": "powerful",
    "exceptionally useful": "useful",
}

# ── PASS 4: Discourse markers to randomly prepend to paragraphs ───────────────
DISCOURSE_MARKERS = [
    "That said, ",
    "In practice, ",
    "Worth noting here — ",
    "To be clear, ",
    "On reflection, ",
    "In our experience, ",
    "Looking at this closely, ",
    "This is where it gets interesting — ",
    "From a practical standpoint, ",
    "At this stage, ",
    "Stepping back, ",
    "Concretely, ",
    "In real terms, ",
    "Thinking through this further, ",
    "As it turned out, ",
    "Interestingly enough, ",
    "To be fair, ",
    "If we're honest about it, ",
    "Looking back, ",
    "What's striking here is that ",
    "The challenge, of course, was ",
    "Not surprisingly, ",
    "More importantly, ",
    "What this really means is that ",
    "Practically speaking, ",
    "To put this differently, ",
    "The thing is, ",
    "What we found, in practice, was that ",
    "On closer inspection, ",
    "When you look at it carefully, ",
]

# ── PASS 5: Contractions map ──────────────────────────────────────────────────
CONTRACTIONS = {
    " do not ": " don't ",
    " does not ": " doesn't ",
    " did not ": " didn't ",
    " is not ": " isn't ",
    " are not ": " aren't ",
    " was not ": " wasn't ",
    " were not ": " weren't ",
    " have not ": " haven't ",
    " has not ": " hasn't ",
    " had not ": " hadn't ",
    " will not ": " won't ",
    " would not ": " wouldn't ",
    " cannot ": " can't ",
    " could not ": " couldn't ",
    " should not ": " shouldn't ",
    " it is ": " it's ",
    " we are ": " we're ",
    " they are ": " they're ",
    " we have ": " we've ",
    " they have ": " they've ",
    " you have ": " you've ",
    " I have ": " I've ",
    " we will ": " we'll ",
    " they will ": " they'll ",
    " that is ": " that's ",
    " there is ": " there's ",
    " what is ": " what's ",
    " who is ": " who's ",
    " would have ": " would've ",
    " could have ": " could've ",
    " should have ": " should've ",
    " might have ": " might've ",
    " must have ": " must've ",
    " we would ": " we'd ",
    " they would ": " they'd ",
    " he would ": " he'd ",
    " she would ": " she'd ",
}

# ── PASS 6: Passive → Active voice patterns ───────────────────────────────────
PASSIVE_TO_ACTIVE = {
    "is being used": "is used",
    "are being used": "are used",
    "was being used": "was used",
    "is being developed": "is in development",
    "is being processed": "is processed",
    "can be utilized": "can be used",
    "can be leveraged": "can be used",
    "has been designed": "was designed",
    "have been designed": "were designed",
    "has been developed": "was built",
    "have been developed": "were built",
    "has been implemented": "was implemented",
    "have been implemented": "were implemented",
    "is being tracked": "gets tracked",
    "are being tracked": "get tracked",
    "is being monitored": "gets monitored",
    "are being monitored": "get monitored",
    "is being maintained": "is maintained",
    "are being maintained": "are maintained",
    "has been established": "was established",
    "have been established": "were established",
    "has been identified": "was identified",
    "have been identified": "were identified",
    "has been introduced": "was introduced",
    "have been introduced": "were introduced",
    "has been created": "was created",
    "have been created": "were created",
    "has been built": "was built",
    "have been built": "were built",
    "has been integrated": "was integrated",
    "have been integrated": "were integrated",
    "is being handled": "is handled",
    "are being handled": "are handled",
    "is being managed": "is managed",
    "are being managed": "are managed",
}

# ── PASS 8: Hedging language to inject randomly ───────────────────────────────
# These replace confident AI assertions with human-like hedged versions
HEDGE_TRIGGERS = {
    # When these confident phrases appear, prepend a hedge
    " is the best ": " is arguably the best ",
    " is the most ": " is arguably the most ",
    " is the only ": " is perhaps the only ",
    " is the key ": " is arguably the key ",
    " is essential": " is arguably essential",
    " is necessary": " is arguably necessary",
    " is critical": " is arguably critical",
    " is fundamental": " is, at its core, fundamental",
    " is clear ": " seems clear ",
    " is obvious ": " appears obvious ",
    " is evident ": " seems evident ",
    " will definitely ": " will likely ",
    " will certainly ": " should ",
    " will always ": " will generally ",
    " will never ": " rarely ",
    " always results in": " tends to result in",
    " always leads to": " often leads to",
    " always ensures": " generally ensures",
    " definitely ": " almost certainly ",
    " certainly ": " likely ",
    " without question ": " arguably ",
    "must be noted": "is worth noting",
}

# ── PASS 9: Parenthetical asides (inject into long sentences) ─────────────────
# These are inserted at clause boundaries to mimic human tangential thinking
PARENTHETICALS = [
    " (and this is important)",
    " (at least in our case)",
    " (which is harder than it sounds)",
    " (though not always straightforward)",
    " (and this was a key insight)",
    " (which took some trial and error)",
    " (something we discovered fairly late)",
    " (not to be underestimated)",
    " (worth pausing on)",
    " (a detail that matters more than it seems)",
    " (this turned out to be crucial)",
    " (and this surprised us somewhat)",
    " (in hindsight)",
    " (which we verified manually)",
    " (this is an open question)",
    " (though your results may vary)",
]

# ── PASS 10: Self-correction micro-patterns ────────────────────────────────────
# Replace some conjunctions with human self-correction patterns
SELF_CORRECTIONS = {
    ". This ": ". Or rather, this ",
    ". The ": ". More precisely, the ",
    ". It ": ". To be specific, it ",
    ". We ": ". To put it another way, we ",
    ". In ": ". More accurately, in ",
}

# ── PASS 11: Personal voice injections ────────────────────────────────────────
# Replace impersonal observations with personal-voice versions
PERSONAL_VOICE = {
    "one can observe": "we observed",
    "one can see": "we found",
    "one can note": "we noted",
    "one might argue": "we'd argue",
    "one could argue": "we'd argue",
    "one should consider": "it's worth considering",
    "one must consider": "we had to consider",
    "it can be seen": "we can see",
    "it can be observed": "we observed",
    "it can be argued": "one could argue",
    "it may be argued": "arguably,",
    "there is a need": "we need",
    "there is a requirement": "there's a requirement",
    "there exists": "there's",
    "there exist": "there are",
    "the need for": "our need for",
    "the importance of": "why it matters — specifically",
    "the role of": "what role",
    "the purpose of": "what",
    "the goal of": "our goal with",
    "the objective of": "our aim with",
    "the aim of": "our aim with",
}

# ── PASS 12: Qualifier injections ─────────────────────────────────────────────
# Replace absolute/certain terms with qualified human-like ones
QUALIFIERS = {
    "all students": "most students",
    "all users": "most users",
    "all cases": "most cases",
    "all instances": "most instances",
    "always works": "generally works",
    "always performs": "generally performs",
    "never fails": "rarely fails",
    "completely eliminates": "largely eliminates",
    "fully automates": "largely automates",
    "fully integrates": "integrates",
    "perfectly matches": "closely matches",
    "perfectly aligns": "largely aligns",
    "entirely new": "largely new",
    "entirely different": "quite different",
    "completely different": "quite different",
    "completely solves": "largely addresses",
    "completely removes": "largely removes",
    "completely replaces": "largely replaces",
    "is solved by": "is largely addressed by",
    "is fixed by": "is largely fixed by",
    "is resolved by": "is largely resolved by",
}

# ── PASS 13: Punctuation humanization patterns ────────────────────────────────
# Replace bland conjunctions with richer punctuation
PUNCTUATION_HUMANIZE = {
    ", and this ": " — and this ",
    ", and it ": " — and it ",
    ", and we ": " — and we ",
    ", and the ": "; the ",
    ". However, ": ". That said, ",
    ". Furthermore, ": ". Also, ",
    ". Moreover, ": ". What's more, ",
    ". Additionally, ": ". On top of that, ",
    ". In addition, ": ". Beyond that, ",
    ". As a result, ": ". So ",
    ". Therefore, ": ". So ",
    ". Thus, ": ". As a result, ",
    ". Subsequently, ": ". After that, ",
    ". Consequently, ": ". The result was that ",
    ". Nevertheless, ": ". That said, ",
    ". Nonetheless, ": ". Even so, ",
    ". Notwithstanding, ": ". Despite that, ",
    ". In contrast, ": ". On the other hand, ",
    ". On the contrary, ": ". In contrast, ",
    ". In comparison, ": ". Compared to that, ",
    ". Specifically, ": ". In particular, ",
    ". Notably, ": ". Worth noting — ",
    ". Importantly, ": ". Critically, ",
}

# ── PASS 14: Syntactic fronting patterns (Signal 5 — Syntactic Patterns) ──────
# Turnitin measures repetitive Subject-Verb-Object structure.
# Fronted adverbials and cleft sentences break this pattern.
# Format: (regex_pattern, replacement_template)
# We handle these with regex in the pipeline, not simple dict replacement.
FRONTING_PATTERNS = [
    # "We implemented X to achieve Y" → "To achieve Y, we implemented X"
    (r'We ([a-z]+ed) (.+?) to ([a-z])', r'To \3, we \1 \2 to'),
    # "It is important that X" → "What matters is that X"
    (r'[Ii]t is important that', 'What matters here is that'),
    (r'[Ii]t is essential that', 'What is essential is that'),
    (r'[Ii]t is crucial that', 'What is crucial is that'),
    (r'[Ii]t is necessary that', 'What is necessary is that'),
    # "The system was designed to X" → "Designed to X, the system"
    # (handled separately in pipeline due to complexity)
]

# Simple fronting swaps — applied like a dict (source → replacement)
SYNTACTIC_FRONTING = {
    # "X is the reason why" → "This is why X"
    "This is the reason why ": "Which is why ",
    "That is the reason why ": "Which is why ",
    # Cleft constructions — add variety
    "What this means is ": "In practical terms, ",
    "What we found was ": "Our finding was that ",
    "What is needed is ": "The need here is for ",
    "What is required is ": "The requirement is ",
    "What makes this work is ": "The key to this is ",
    "What sets this apart is ": "The differentiator here is ",
    # Fronted "given that" / "since"
    "The reason for this is that ": "Since ",
    "The reason behind this is that ": "Given that ",
    "The reason this works is that ": "This works because ",
    # Appositive patterns (break up noun phrases)
    "the Rayvoy Overseas CRM system ": "the CRM — our main tool — ",
    "the Rayvoy CRM system ": "the CRM — our main tool — ",
    "the proposed CRM system ": "the proposed CRM (our main tool) ",
    "the student management system ": "the student management system — built in-house — ",
    # Inverted emphasis
    "is the most important": "matters the most",
    "is the least important": "matters the least",
    "is the main reason": "is why, primarily,",
    "is the primary reason": "is the main reason — and this is key —",
    # Fronted time expressions that AI buries in the middle
    "we started by ": "To begin, we ",
    "we began by ": "Starting out, we ",
    "we decided to ": "The decision was to ",
    "we chose to ": "Our choice was to ",
    "we opted to ": "We went with ",
    "we selected ": "Our selection was ",
    "we identified ": "What we identified was ",
    "we noticed ": "What we noticed was ",
    "we observed ": "Our observation was that ",
    "we confirmed ": "What we confirmed was that ",
    "we determined ": "Our determination was that ",
    "we concluded ": "The conclusion we reached was that ",
    "we realized ": "At some point, we realized ",
    "we recognized ": "It became clear to us that ",
}

# ── PASS 16: Imperfect discourse — conjunction openers (Signal 4) ──────────────
# Humans start sentences and paragraphs with And/But/Yet/Or.
# AI is trained to NEVER do this. It's one of the clearest human markers.
# These are prepended to ~8% of substantive paragraphs.
CONJUNCTION_OPENERS = [
    "And ",
    "But ",
    "Yet ",
    "Or, ",
    "Still, ",
    "Even so, ",
    "And yet, ",
    "But then again, ",
    "Or rather, ",
    "And this is worth emphasizing — ",
    "But what's interesting is that ",
    "Yet in practice, ",
    "And in our experience, ",
    "But the reality is that ",
]

# ── PASS 14 EXTRA: Adverbial fronting patterns ────────────────────────────────
# "We X because Y" → "Because Y, we X"  (regex-based, handled in pipeline)
# "X is Y in Z context" → "In Z context, X is Y"
ADVERBIAL_FRONTING = {
    "In many cases, ": "Often, ",
    "In most cases, ": "Typically, ",
    "In some cases, ": "Sometimes, ",
    "In all cases, ": "In every case, ",
    "In this case, ": "Here, ",
    "In such cases, ": "When this happens, ",
    "In general, ": "Generally, ",
    "In particular, ": "Specifically, ",
    "In practice, ": "Practically, ",
    "In theory, ": "Theoretically, ",
    "In reality, ": "In truth, ",
    "In fact, ": "Actually, ",
    "In essence, ": "At its core, ",
    "In addition to this, ": "Beyond that, ",
    "In contrast to this, ": "Compared to that, ",
    "In terms of performance, ": "Performance-wise, ",
    "In terms of security, ": "From a security angle, ",
    "In terms of usability, ": "For usability, ",
    "In terms of scalability, ": "For scalability, ",
    "At the same time, ": "Simultaneously, ",
    "At this point, ": "Here, ",
    "At this stage, ": "At this point, ",
    "Under normal circumstances, ": "Normally, ",
    "Under these circumstances, ": "Given this, ",
    "Under this framework, ": "Within this structure, ",
    "From a user perspective, ": "For users, ",
    "From a technical perspective, ": "Technically, ",
    "From a business perspective, ": "For the business, ",
    "From a security perspective, ": "Security-wise, ",
    "From a design perspective, ": "Design-wise, ",
}

IDIOMATIC_INJECTIONS = {
    "in conclusion": ["at the end of the day", "when all is said and done"],
    "however": ["that being said", "then again", "having said that"],
    "furthermore": ["to top it off", "on top of that"],
    "therefore": ["because of this", "so, naturally,"],
    "additionally": ["not to mention,", "as a bonus,"],
    "in summary": ["long story short,", "the bottom line is"]
}
